package com.xworkz.constant;

public enum WeaponType {
	
	ARTILLERY_WEAPON, CHEMICAL_WEAPONS, HAND_TO_HAND_WEAPON, EXPLOSIVES,MISSILES,
	SEMIAUTOMATIC_WEAPONS, AUTOMATIC_WEAPONS, NUCLEAR_WEAPONS,
	

}
